# This is a basic workflow to help you get started with Actions

name: CI 🚆

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_React_Hotel_Miranda:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello hotel Miranda Build!

      # Runs a set of commands using the runners shell
      - name: Install and Build 🔧 multi-line script
        run: |
          yarn
          yarn build
        env:
          CI: false

      # Run Jest tests!
      - name: Run  tests 🧪
        run: yarn test

      - name: Deploy 🏭
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to. It should NEVER Deploy to Main!!!!!!!
          folder: build # The folder the action should deploy.
          
  curl_job:
    needs: build_React_Hotel_Miranda
    name: curl
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://sebainones.github.io/ReactTicTacToeApp/
